[package]
name = "rust-starter"
version = "0.1.0"
authors = ["Max Trense <dev@trense.info>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
frank_jwt = "3.1.0"
clap = "2.32.0"
serde_derive = "1.0.89"
serde = "1.0.89"
serde_json = "1.0.39"
env_logger = "0.6.0"